### PR TITLE
Add videoenhancement machine feature

### PR DESCRIPTION
**Pull request by persianpros**
Add videoenhancement machine feature
* Update hd11.conf
* Update hd1100.conf
* Update hd1200.conf
* Update hd1265.conf
* Update hd1500.conf
* Update hd500c.conf
* Update hd530c.conf
* Update vs1000.conf
* Update hd2400.conf

### CODE REVIEW

**Comment by HD-Digital** [comment]
videoenhancement I cannot find in the build options:
https://github.com/OpenPLi/openpli-oe-core/tree/develop/meta-openpli/recipes-openpli/images

Please tell me why we should have this option?

**Comment by persianpros** [comment]
It will be used for:

	${@bb.utils.contains("MACHINE_FEATURES", "videoenhancement", "", "enigma2-plugin-systemplugins-videoenhancement", d)} \

**Comment by HD-Digital** [comment]
Please inform me were this setting can been found on https://github.com/openpli
As quick search doesn't give any hit that this setting is used in Openpli..

**Comment by HD-Digital** [comment]
No feedback and we can see nowhere that this function is used

**Pull request closed without merging**
